### ISSUE TITLE
Obtaining lowest power baseline on the nRF9160

### ISSUE THREAD

**Issue by eflukx** [diondokter/nrf-modem#15]
This possibly is a bit off topic, but planning to use nrf-modem/embassy with this project (currently, the FW is still RTIC based)... Hoping to find someone here to enlighten me.. 🥇 

I'm (tenaciously) trying to get my battery-powered nRF9160-based embedded system to the lowest power state possible. I eliminated as much as possible, hardware wise by removing/disconnecting most of the surrounding circuitry (basically only the nRF9160 SOM itself and the (low Iq) power supply is left).
I'm trying to get to a baseline (minimum) power use where the system essentially does nothing but idling/sleeping, in order to step-by-step add/enable more functionality and hardware coming from this baseline (while closely monitoring power use).

Up till now I don't seem to get below the 250µA mark, idling with Rust (e.g. https://github.com/diondokter/nrf91-2.0.1-test with a sleep loop at the end). Way too high for my battery powered system. 🤷🏻 To get the baseline straight, I reverted to the _nRF Connect SDK_ hoping to find the answer there (SDK needed anyway to build the SPM). The UDP example from the SDK gets me down to 40-60µA and a also found some "do nothing only sleep" low power code example (somewhere on the Nordic forum) that brings the current draw down to ~4µA. Everything below 10µA would be acceptable for me. At least our custom hardware seems to be capable of going low (enough)... 

Maybe someone could shine his/her light on this. Possibly my SPM is enabling something that causes the excessive power draw. What would be very helpful is a Rust example for the nRF9160 that yields a very low power draw (preferably with the SPM included). So that others (including me 😄) can use that as a power-baseline in the nRF9160+Rust world.. :)

Any help is appreciated !

_Note: Don't focus too much on the actual absolute measured current values, as there's a DC-DC buck converter on the board. Measurements done using a Nordic PPK2_

**Comment by diondokter** [comment]
Hi!

Interesting question.

250uA is indeed way to much.
So, how the library works is that the modem is automatically managed. So if you create a socket, the modem will be started.
The modem will be turned off when all sockets and gps (and LteLinks) are dropped.

So make sure you've done that!
If you do, it should be a lot better.

**Comment by diondokter** [comment]
Btw, this library never deinitializes the modem. I don't know if that would save more power, you could try that out by manually calling https://docs.rs/nrfxlib-sys/latest/nrfxlib_sys/fn.nrf_modem_shutdown.html

If you do, please let me know if anything changes!

**Comment by dkhayes117** [comment]
The lowest I was able to achieve was 115 uA sleep current, but I didn't try super hard.  I basically had to disconnect pin 29 because the dev board I used had some on-board sensors.  I also disabled UARTE0, UARTE1, and the socket before sleeping, which probably wasn't necessary and is limited to a fixed amount of connections/hr that the cell tower will allow.  The correct way is to let PSM and eDRX handle modem sleeping.  I've been meaning to get around back to optimizing this more with PSM but haven't got there yet.   Note that just because you set PSM or eDRX to certain settings does not mean that the network supports those settings.  https://devzone.nordicsemi.com/f/nordic-q-a/70495/use-ppk2-testing-nrf9160-psm-and-edrx-power-consumption
```rust
    // // Disable UARTE for lower power consumption
    let uarte0: UARTE0 = unsafe { core::mem::transmute(()) };
    let uarte1: UARTE1 = unsafe { core::mem::transmute(()) };
    uarte0.enable.write(|w| w.enable().disabled());
    uarte1.enable.write(|w| w.enable().disabled());
    // do some stuff
    socket.deactivate().await?;
```

**Comment by eflukx** [comment]
@diondokter Sorry my attention was taken by other tasks🚧 ... so I completely missed your replies. 

> 250uA is indeed way to much. So, how the library works is that the modem is automatically managed. So if you create a socket, the modem will be started. The modem will be turned off when all sockets and gps (and LteLinks) are dropped.
> So make sure you've done that! If you do, it should be a lot better.

Will setup a new test with the and will let you know the results. Do you have experience with using different PSM-binaries (in regards to power use)?

As @dkhayes117 mentions, it is best to let the modem manage its power by using PSM/eDRX. How does this work together with your remark  _"The modem will be turned off when all sockets and gps (and LteLinks) are dropped."_ Is PSM used or is the modem actively managed by the application (i.e. the `nrf-modem` crate)

**Comment by diondokter** [comment]
> @diondokter Sorry my attention was taken by other tasks🚧 ... so I completely missed your replies. 
> 
> > 250uA is indeed way to much. So, how the library works is that the modem is automatically managed. So if you create a socket, the modem will be started. The modem will be turned off when all sockets and gps (and LteLinks) are dropped.
> > So make sure you've done that! If you do, it should be a lot better.
> 
> Will setup a new test with the and will let you know the results. Do you have experience with using different PSM-binaries (in regards to power use)?
> 
> As @dkhayes117 mentions, it is best to let the modem manage its power by using PSM/eDRX. How does this work together with your remark  _"The modem will be turned off when all sockets and gps (and LteLinks) are dropped."_ Is PSM used or is the modem actively managed by the application (i.e. the `nrf-modem` crate)

In principle the modem is turned on and off by the library. PSM is only relevant when the modem is on.

**Comment by eflukx** [comment]
Hmm.. I made a (power-) testing PCB with almost nothing soldered, just the nRF9160 and some decouple caps. (no peripherals, no PSU nothing..) Somehow my idle use is in the _milliamps_ (about 3.7mA @3.3V).. 😒 I must be missing something obvious here... 

Testing with an absolutely barebones embassy "application" (based on  https://github.com/diondokter/nrf91-2.0.1-test.git) gets me the 3.7mA.. That is with the included 'zephyr.bin' SPM in said repo. I also have my own SPM ('my_zephyr.bin'), which brings the power use down to 2.8mA.. That's an improvement, but still way too high. I've been fiddling about with getting a 'low power SPM', but without great success until now...
Could someone share an SPM that is known to get into low-power-territory? Or better even: a small (bare-bones, no functionality needed) Rust project for the nRF9160 with an SPM included that offers/shows low power, so I have a starting point to take take things from... 

Your help is very much appreciated...! 🙇🏻‍♂️ 

My barebones app:

```rust
#![no_main]
#![no_std]
#![feature(type_alias_impl_trait)]

use cortex_m_rt::ExceptionFrame;
use defmt_rtt as _;
use embassy_nrf::interrupt;
use panic_probe as _;

#[embassy_executor::main]
async fn main(_spawner: embassy_executor::Spawner) {
    defmt::println!("Hello, world!");

    loop {
        cortex_m::asm::wfi();
    }
}

#[defmt::panic_handler]
fn panic() -> ! {
    cortex_m::asm::udf()
}

#[cortex_m_rt::exception]
unsafe fn HardFault(e: &ExceptionFrame) -> ! {
    defmt::error!("HardFault: {}", defmt::Debug2Format(e));

    loop {
        cortex_m::asm::bkpt();
    }
}

#[link_section = ".spm"]
#[used]
static SPM: [u8; 24052] = *include_bytes!("../zephyr.bin");

```

**Comment by diondokter** [comment]
@eflukx Huh strange. My guess is that your SPM turns on some peripheral.
In our old project we had a function that forces everything off:

```rust
/// Set all peripherals in a 'fresh' state, i.e. disabled.
pub fn fresh(p: &Peripherals) {
    unsafe {
        p.UARTE0_NS
            .enable
            .write_with_zero(|w| w.enable().disabled());
        p.UARTE1_NS
            .enable
            .write_with_zero(|w| w.enable().disabled());
        p.UARTE2_NS
            .enable
            .write_with_zero(|w| w.enable().disabled());
        p.UARTE3_NS
            .enable
            .write_with_zero(|w| w.enable().disabled());
        p.TWIM0_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.TWIM1_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.TWIM2_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.TWIM3_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.TWIS0_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.TWIS1_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.TWIS2_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.TWIS3_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.SPIM0_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.SPIM1_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.SPIM2_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.SPIM3_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.SPIS0_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.SPIS1_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.SPIS2_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.SPIS3_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.PWM0_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.PWM1_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.PWM2_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.PWM3_NS.enable.write_with_zero(|w| w.enable().disabled());
        p.SAADC_NS.enable.write_with_zero(|w| w.enable().disabled());

        // Note: disabling these two peripherals will increase power consumption drastically
        // for an unknown reason.
        //
        // p.PDM_NS.enable.write_with_zero(|w| w.enable().disabled());
        // p.I2S_NS.enable.write_with_zero(|w| w.enable().disabled());
        // anomalies::workaround_1_i2s_stop();

        p.TIMER0_NS
            .tasks_stop
            .write_with_zero(|w| w.tasks_stop().trigger());
        p.TIMER1_NS
            .tasks_stop
            .write_with_zero(|w| w.tasks_stop().trigger());
        p.TIMER2_NS
            .tasks_stop
            .write_with_zero(|w| w.tasks_stop().trigger());
        p.RTC0_NS
            .tasks_stop
            .write_with_zero(|w| w.tasks_stop().trigger());
        p.RTC1_NS
            .tasks_stop
            .write_with_zero(|w| w.tasks_stop().trigger());
    }
}
```

This was with the nrf-hal, not the embassy hal/pac.
See if doing this works.

**Comment by eflukx** [comment]
Ok thanks.. app was reduced to this (no Embassy this time)...
We're still @2.7mA 😦 

```rust
use bsp::hal as _;

#[cortex_m_rt::entry]
fn main() -> ! {
    fresh(&bsp::hal::pac::Peripherals::take().unwrap());

    loop {
        defmt::println!("Hello, world! DONE");
        asm::wfe();
    }
}
```

**Comment by diondokter** [comment]
@eflukx what happens when you put the chip in systemoff mode?

```rust
loop {
    peripherals.POWER.systemoff.write(|w| w.systemoff().set_bit());
}
```

(Don't worry, you can start new debug session just fine in this sleep. It will be recoverable)

With this it should fall to <50uA (possibly even <10uA depending on how efficient your power supply is).

One critical thing though is that when measuring the current, you have to make sure that the debug logic of the chip is off.
To do that, flash the firmware onto the device, remove your debug probe fully and reset the microcontroller. Reset should be enough (not for STM, they require a full power off)

**Comment by eflukx** [comment]
Yep. I'm aware the debug circuitry take some mA's and typically some stray currents go through the debugger as well. I follow a procedure similar to as you describe: power-cycling the device before measuring the actual current.

The `systemoff` functionality does not seem to be available on nRF9160 AFAIK, i guess the code snippet is from a nRF528xx mcu(?) (where indeed shutting off the system leads to the absolute lowest power use.. :)

The nRF9160 can be powered off externally by tying both _ENABLE_ and _GPIO_VDD_ to ground. (unfortunately, that is pretty hard to do on my board, not impossible, but I don't have the proper tools at hand currently..)

The ~2.5mA were seeing, suspiciously matches the (documented) power use of the CPU core.. could it be something keeps it running? 
Would it be possible the SPM enables some `xxxxx_S` (secure) device, which can't be disabled anymore from the `_NS` side of things?

**Comment by diondokter** [comment]
Ah whoops, I did indeed copy from the nrf52 because I thought they were the same, but on the nrf91 it's in a different peripheral:

```rust
            loop {
                unsafe { &*embassy_nrf::pac::REGULATORS::PTR }
                    .systemoff
                    .write(|w| w.systemoff().enable());
            }
```

In my experience `wfi` works better than `wfe`.

The SPM shouldn't do anything really. It's basically a bootloader that puts everything in non-secure mode and the jumps to your application. Only thing is that it can leave peripherals initialized, but we've already seen that that's not the (full) solution

**Comment by eflukx** [comment]
WTF... when switching off the regulators, the power use **remains** the exact same 2.7mA I'm getting most of the time.. 🤯 

This made me suspicious about the hardware.. the issue is I _do_ have an example from the _Nordic Connect SDK_ that brings power down to *4 µA*!, pretty sweet.. So somehow the hardware _is_ capable of running with really low power use.. (i.e. no shorts or whatever) Really stumped how I'm not able to achieve the same in Rust land...

code of the example running @4µA.. (nothing to see here...)

```C
#include <zephyr/kernel.h>

void main(void)
{
    printk("Hello World! %s\n", CONFIG_BOARD);
}
```

**Comment by diondokter** [comment]
Huh, that's really weird.

Let's strip out the SPM then. You only need that to go into non-secure mode (which is the mode you need to be in to talk to the modem). If you need HAL support, then use the Embassy HAL. It has everything available in secure mode too.

**Comment by diondokter** [comment]
I don't know. I've never used TFM. But still you don't need it. Just boot the chip without anything else.
Flash starts at 0. RAM, you could use all the ram, but the current numbers work

**Comment by eflukx** [comment]
Opened a ticket with Nordic, to see if they can help... 🤞🏻 
https://devzone.nordicsemi.com/f/nordic-q-a/103447/unable-to-obtain-low-power-use-when-idle

I'll keep this ticket updated when I find the root cause.. (for future reference)

One thing that has been cleared is the higher power use when the modem isn't inited. Apparently there's an erratum for the nRF9160 that causes the modem to use up a lot of power (in my case ~1mA) when it isn't initialized.

**Comment by eflukx** [comment]
Ok.. I found the leak! It was a "mitigation" for a [hardware erratum](https://infocenter.nordicsemi.com/index.jsp?topic=%2Ferrata_nRF9160_EngA%2FERR%2FnRF9160%2FEngineeringA%2Flatest%2Fanomaly_160_17.html), that caused the excessive draw. Whomever is interested, see [this Nordic ticket](https://devzone.nordicsemi.com/f/nordic-q-a/103447/unable-to-obtain-low-power-use-when-idle) for the full story.

@diondokter Thanks very much for your time and effort looking over my shoulder! 💪🏻

**Comment by diondokter** [comment]
Ah great! No problem :)
