### ISSUE TITLE
blocking drop

### ISSUE THREAD

**Issue by macthestack** [diondokter/nrf-modem#2]
Blocking on drop is not great.

Without being able to drop asynchronously, could we add async functions that takes "self" to allow for manual deactivation? The drop would not need to do anything if ACTIVE_LINKS is 0 but would behave the same otherwise.

**Comment by diondokter** [comment]
The blocking is not very nice no. A manual async deactivation would be great IMO! As long as the normal drop still exists and is functional like you said.
